# To start all docker containers run: `docker-compose up`
#
version: '3'
services:
  app:
    build: .
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app:cached
      - gem_cache:/gems
    env_file:
      - .dockerenv/database
      - .dockerenv/services
    tty: true
    environment:
      - SKYLIGHT_DISABLE_DEV_WARNING=true
    stdin_open: true

  sidekiq:
    build: .
    command: bash -c "bundle && bundle exec sidekiq --config config/sidekiq.yml > log/sidekiq.log"
    depends_on:
      - db
      - redis
    env_file:
      - .dockerenv/database
      - .dockerenv/services
    volumes:
      - .:/app:cached
      - gem_cache_sidekiq:/gems

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    env_file:
      - .dockerenv/database
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      driver: none

  redis:
    image: redis
    volumes:
      - redis:/data
volumes:
  db-data:
    driver: local
  gem_cache: {}
  gem_cache_sidekiq: {}
  redis: {}
